---
abstract: "Patch perl source a la Devel::PPort's buildperl.pl"
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200006, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-PatchPerl
requires:
  File::pushd: 1.00
  IO::File: 0
  IPC::Cmd: 0.40
  MIME::Base64: 0
  perl: v5.6.0
resources:
  homepage: http://github.com/bingos/devel-patchperl
  repository: http://github.com/bingos/devel-patchperl
version: 0.34
